runtime: python
env: flex

entrypoint: gunicorn -b :$PORT -k eventlet -w 1 main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://wedday:weddaysecret@/wedday?unix_socket=/cloudsql/cosmos-369:asia-east1:wedday-db

beta_settings:
  cloud_sql_instances: cosmos-369:asia-east1:wedday-db

network:
  session_affinity: true
